#!/bin/bash

# Install system dependencies
sudo apt-get update
sudo apt-get install -y libffi-dev libssl-dev build-essential python3.4-dev libpython3-dev

# Install Python 3.7
sudo apt-get install -y python3.7 python3.7-dev

# Install virtualenv
sudo apt-get install -y python3-pip
sudo pip3 install virtualenv

# Create and activate virtual environment
virtualenv -p python3.7 myenv
source myenv/bin/activate

# Upgrade pip
pip install --upgrade pip

# Install dependencies
pip install pyparsing
pip install appdirs
pip install setuptools==40.1.0
pip install cryptography==2.8
pip install bcrypt==3.1.7
pip install PyNaCl==1.3.0
pip install Fabric3==1.14.post1

# Deactivate virtual environment
deactivate

